import type { Metadata } from "next";
import "./globals.css";
import { UserProfileProvider } from "./context/UserProfileContext";

export const metadata: Metadata = {
  title: "Innernet - Keep Your Inner Mood",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProfileProvider>{children}</UserProfileProvider>
      </body>
    </html>
  );
}
