import type { Metadata } from "next";
import "./globals.css";
import { UserProfileProvider } from "./context/UserProfileContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Innernet - DEV APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <UserProfileProvider>{children}</UserProfileProvider>
      </body>
    </html>
  );
}
